/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as LearnCourseSlugRouteImport } from './routes/learn.$courseSlug'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as LearnCourseSlugLessonSlugRouteImport } from './routes/learn.$courseSlug.$lessonSlug'
import { Route as CertificateUsernameCertificateSlugRouteImport } from './routes/certificate.$username.$certificateSlug'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseSlugRoute = LearnCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => LearnRoute,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const LearnCourseSlugLessonSlugRoute =
  LearnCourseSlugLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => LearnCourseSlugRoute,
  } as any)
const CertificateUsernameCertificateSlugRoute =
  CertificateUsernameCertificateSlugRouteImport.update({
    id: '/certificate/$username/$certificateSlug',
    path: '/certificate/$username/$certificateSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$id': typeof CoursesIdRoute
  '/learn/$courseSlug': typeof LearnCourseSlugRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/certificate/$username/$certificateSlug': typeof CertificateUsernameCertificateSlugRoute
  '/learn/$courseSlug/$lessonSlug': typeof LearnCourseSlugLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$id': typeof CoursesIdRoute
  '/learn/$courseSlug': typeof LearnCourseSlugRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/certificate/$username/$certificateSlug': typeof CertificateUsernameCertificateSlugRoute
  '/learn/$courseSlug/$lessonSlug': typeof LearnCourseSlugLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/learn': typeof LearnRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$id': typeof CoursesIdRoute
  '/learn/$courseSlug': typeof LearnCourseSlugRouteWithChildren
  '/profile/$username': typeof ProfileUsernameRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/certificate/$username/$certificateSlug': typeof CertificateUsernameCertificateSlugRoute
  '/learn/$courseSlug/$lessonSlug': typeof LearnCourseSlugLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/forgot-password'
    | '/learn'
    | '/login'
    | '/register'
    | '/admin/courses'
    | '/admin/users'
    | '/courses/$id'
    | '/learn/$courseSlug'
    | '/profile/$username'
    | '/settings/account'
    | '/settings/profile'
    | '/certificate/$username/$certificateSlug'
    | '/learn/$courseSlug/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/forgot-password'
    | '/learn'
    | '/login'
    | '/register'
    | '/admin/courses'
    | '/admin/users'
    | '/courses/$id'
    | '/learn/$courseSlug'
    | '/profile/$username'
    | '/settings/account'
    | '/settings/profile'
    | '/certificate/$username/$certificateSlug'
    | '/learn/$courseSlug/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/dashboard'
    | '/forgot-password'
    | '/learn'
    | '/login'
    | '/register'
    | '/admin/courses'
    | '/admin/users'
    | '/courses/$id'
    | '/learn/$courseSlug'
    | '/profile/$username'
    | '/settings/account'
    | '/settings/profile'
    | '/certificate/$username/$certificateSlug'
    | '/learn/$courseSlug/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LearnRoute: typeof LearnRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  CertificateUsernameCertificateSlugRoute: typeof CertificateUsernameCertificateSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseSlug': {
      id: '/learn/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/learn/$courseSlug'
      preLoaderRoute: typeof LearnCourseSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/learn/$courseSlug/$lessonSlug': {
      id: '/learn/$courseSlug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/learn/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof LearnCourseSlugLessonSlugRouteImport
      parentRoute: typeof LearnCourseSlugRoute
    }
    '/certificate/$username/$certificateSlug': {
      id: '/certificate/$username/$certificateSlug'
      path: '/certificate/$username/$certificateSlug'
      fullPath: '/certificate/$username/$certificateSlug'
      preLoaderRoute: typeof CertificateUsernameCertificateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCoursesRoute: AdminCoursesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesIdRoute: typeof CoursesIdRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesIdRoute: CoursesIdRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface LearnCourseSlugRouteChildren {
  LearnCourseSlugLessonSlugRoute: typeof LearnCourseSlugLessonSlugRoute
}

const LearnCourseSlugRouteChildren: LearnCourseSlugRouteChildren = {
  LearnCourseSlugLessonSlugRoute: LearnCourseSlugLessonSlugRoute,
}

const LearnCourseSlugRouteWithChildren = LearnCourseSlugRoute._addFileChildren(
  LearnCourseSlugRouteChildren,
)

interface LearnRouteChildren {
  LearnCourseSlugRoute: typeof LearnCourseSlugRouteWithChildren
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnCourseSlugRoute: LearnCourseSlugRouteWithChildren,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LearnRoute: LearnRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  CertificateUsernameCertificateSlugRoute:
    CertificateUsernameCertificateSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
